apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: authorize-tls-user
  labels:
    strimzi.io/cluster: authorize-tls-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: authortls
          patternType: literal
        operation: All
      - resource:
          type: topic
          name: authortls
          patternType: literal
        operation: Describe
      - resource:
          type: group
          name: my-group
          patternType: literal
        operation: Read